core/urls.py
# core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),

    # За нас
    path("about/", views.about, name="about"),
    path("about/base/", views.about_base, name="about_base"),
    path("about/history/", views.about_history, name="about_history"),
    path("about/mission/", views.about_mission, name="about_mission"),
    path("about/team/", views.about_team, name="about_team"),
    path("about/council/", views.about_council, name="about_council"),
    path("about/profile/", views.about_profile, name="about_profile"),

    # Кандидатстване / образование
    path("admission/", views.admission, name="admission"),
    path("education/", views.education, name="education"),

    # За учениците
    path("students/", views.students, name="students"),
    path("students/available_places/", views.students_available_places,
         name="students_available_places"),
    path("students/daily_regime/", views.students_daily_regime,
         name="students_daily_regime"),
    path("students/schedules/", views.students_schedules,
         name="students_schedules"),
    path("students/nvo/", views.students_nvo, name="students_nvo"),
    path("students/dzi/", views.students_dzi, name="students_dzi"),
    path("students/scholarships/", views.students_scholarships,
         name="students_scholarships"),
    #     path("students/diary/", views.students_diary, name="students_diary"),
    path("students/useful_links/", views.students_useful_links,
         name="students_useful_links"),

    # Проекти и програми
    path("projects/", views.projects, name="projects"),

    # Контакти
    path("contacts/", views.contacts, name="contacts"),
]

documents/urls.py
from django.urls import path
from . import views

app_name = "documents"

urlpatterns = [
    path(
        "",
        views.documents_overview,
        name="documents_overview",
    ),
    path(
        "archive/",
        views.documents_archive,
        name="documents_archive",
    ),
    path(
        "<str:category_code>/",
        views.documents_by_category,
        name="documents_by_category",
    ),
]

gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.gallery_list, name="gallery_list"),
    path("<slug:code>/", views.gallery_detail, name="gallery_detail"),
]

news/urls.py
# news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.news, name="news"),
    path("news_list", views.news_list, name="news_list"),
    path("<slug:code>/", views.news_detail, name="news_detail"),
]

newspaper/urls.py
from django.urls import path
from . import views

app_name = "newspaper"

urlpatterns = [
    path("", views.newspaper_list, name="newspaper_list"),
]

core/views.py
# core/views.py
from django.shortcuts import render
from news.models import News


# Основна страница
def home(request):
    latest_news = News.objects.order_by('-created_at')[:3]
    return render(request, 'core/home.html', {
        'latest_news': latest_news,
    })

# За нас


def about(request):
    return render(request, "core/about.html")


def about_base(request):
    return render(request, "core/about_base.html")


def about_history(request):
    return render(request, "core/about_history.html")


def about_mission(request):
    return render(request, "core/about_mission.html")


def about_team(request):
    return render(request, "core/about_team.html")


def about_council(request):
    return render(request, "core/about_council.html")


def about_profile(request):
    return render(request, "core/about_profile.html")


# Други
def admission(request):
    return render(request, "core/admission.html")


def education(request):
    return render(request, "core/education.html")


# За учениците
def students(request):
    return render(request, "core/students.html")


def students_available_places(request):
    return render(request, "core/students_available_places.html")


def students_daily_regime(request):
    return render(request, "core/students_daily_regime.html")


def students_schedules(request):
    return render(request, "core/students_schedules.html")


def students_nvo(request):
    return render(request, "core/students_nvo.html")


def students_dzi(request):
    return render(request, "core/students_dzi.html")


def students_scholarships(request):
    return render(request, "core/students_scholarships.html")


def students_useful_links(request):
    return render(request, "core/students_useful_links.html")


# Проекти и програми
def projects(request):
    return render(request, "core/projects.html")


# Контакти
def contacts(request):
    return render(request, "core/contacts.html")

core/templates/core/includes/documents_list.html
{% if documents %}
    <ul>
        {% for doc in documents %}
        <li>
            <a href="{{ doc.file.url }}" target="_blank">{{ doc.title }}</a>
            {% if doc.description %}
            <small> – {{ doc.description }}</small>
            {% endif %}
            <small> / {{ doc.uploaded_at }}</small>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p><em>Няма документи в тази категория.</em></p>
{% endif %}


{% comment %}
<ul class="document-list">
    {% for doc in documents %}
        <li>
            <a href="{{ doc.file.url }}" target="_blank">{{ doc.title }}</a>
            {% if doc.upload_date %}
                <span class="doc-date">({{ doc.upload_date|date:"d.m.Y" }})</span>
            {% endif %}
        </li>
    {% empty %}
        <li>Няма добавени документи.</li>
    {% endfor %}
</ul>
{% endcomment %}

core/templates/core/includes/footer.html
<footer class="site-footer">
    
    <p>
        &copy; {% now "Y" %} Търговска гимназия "Васил Априлов"
        <span class="school-city"> – Червен бряг</span>
    </p>

</footer>

core/templates/core/includes/header.html
{% load static %}

<header class="site-header">
    <div class="container header-main">
        <a href="{% url 'core:home' %}" class="header-home-link">
            <img src="{% static 'assets/images/logo.png' %}" alt="Logo" class="logo">        
            <h1>
                Търговска гимназия "Васил Априлов"
                <span class="school-city"> – Червен бряг</span>
            </h1>
        </a>
    </div>
</header>

core/templates/core/includes/nav.html
<nav class="main-nav">
    <div class="mobile-nav-bar">
        <span class="mobile-nav-title">Основно меню</span>

        <button class="mobile-nav-toggle" type="button" aria-label="Отвори меню" aria-expanded="false">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>

    <ul>
        <li><a href="{% url 'core:home' %}">Начало</a></li>
        <li class="has-dropdown">
            <a href="{% url 'core:about' %}">За нас</a>
            <ul class="dropdown">
                <li><a href="{% url 'core:about_history' %}">История</a></li>
                <li><a href="{% url 'core:about_base' %}">Материална база</a></li>
                <li><a href="{% url 'core:about_mission' %}">Мисия и визия</a></li>
                <li><a href="{% url 'core:about_team' %}">Екип</a></li>
                <li><a href="{% url 'core:about_council' %}">Обществен съвет</a></li>
                <li><a href="{% url 'core:about_profile' %}">Профил на купувача</a></li>
            </ul>
        </li>

        <li class="has-dropdown">
            <a href="{% url 'documents:documents_overview' %}">Документи</a>
            <ul class="dropdown">
                {% for category in menu_categories %}
                    <li><a href="{% url 'documents:documents_by_category' category.code %}">{{ category.name }}</a></li>
                {% endfor %}

                {% if show_archive %}
                    <li class="divider"></li>
                    <li>
                        <a href="{% url 'documents:documents_archive' %}">
                            📦 Архив ({{ archived_count }})
                        </a>
                    </li>
                {% endif %}
                <!-- <li><a href="{{ menu_archive_url }}">Архив</a></li> -->
            </ul>
        </li>

        <li><a href="{% url 'core:admission' %}">Прием</a></li>
        <li><a href="{% url 'core:education' %}">Обучение</a></li>

        <li class="has-dropdown">
            <a href="{% url 'core:students' %}">За учениците</a>
            <ul class="dropdown">
                <li><a href="{% url 'core:students_available_places' %}">Свободни места</a></li>
                <li><a href="{% url 'core:students_daily_regime' %}">Дневен режим</a></li>
                <li><a href="{% url 'core:students_schedules' %}">Графици</a></li>
                <li><a href="{% url 'core:students_nvo' %}">НВО</a></li>
                <li><a href="{% url 'core:students_dzi' %}">ДЗИ и ЗДИППК</a></li>
                <li><a href="{% url 'core:students_scholarships' %}">Стипендии</a></li>
                <li><a href="{% url 'core:students_useful_links' %}">Полезни връзки</a></li>
            </ul>
        </li>

        <li><a href="{% url 'core:projects' %}">Проекти и програми</a></li>
        <li class="has-dropdown">
            <a href="{% url 'news:news' %}">Новини</a>
            <ul class="dropdown">
                <li><a href="{% url 'news:news_list' %}">Актуални новини</a></li>
                <li><a href="{% url 'newspaper:newspaper_list' %}">Училищен вестник</a></li>
                <li><a href="{% url 'creativity:creativity_list' %}">Творчество</a></li>
            </ul>
        </li>
        <li><a href="{% url 'gallery:gallery_list' %}">Галерия</a></li>
        <li><a href="{% url 'core:contacts' %}">Контакти</a></li>
    </ul>
</nav>

core/templates/core/includes/topbar.html
{% load static %}

<div class="top-bar">
    <div class="container top-bar-content">

        <div class="topbar-contact">
            <a href="tel:065992318"
            class="topbar-icon-link toggle-contact"
            data-target="phone">
                <img src="{% static 'assets/icons/phone.svg' %}" alt="Телефон">
                <span class="contact-text">0659 9 23 18</span>
            </a>

            <a href="mailto:info-1500219@edu.mon.bg"
            class="topbar-icon-link toggle-contact"
            data-target="email">
                <img src="{% static 'assets/icons/email.svg' %}" alt="Имейл">
                <span class="contact-text">info-1500219@edu.mon.bg</span>
            </a>
        </div>

        <div class="topbar-social">
            <a href="https://www.facebook.com/tgvaprilov/" target="_blank" class="topbar-icon-link">
                <img src="{% static 'assets/icons/facebook_burgundy.svg' %}" alt="Facebook">
            </a>
            <a href="https://www.youtube.com/@tgvaprilov" target="_blank" class="topbar-icon-link">
                <img src="{% static 'assets/icons/youtube_burgundy.svg' %}" alt="YouTube">
            </a>
        </div>

    </div>
</div>